@startuml Temporal to Temporal Workflow

== Start Workflow-based ALO ==

actor "Alice's\nWorkflow Worker"
group Service
else Temporal Workflow Service
  "Alice's\nWorkflow Worker" -> "Alice's\nTemporal/Nexus" : Schedule Nexus command
  "Alice's\nTemporal/Nexus" -> "Alice's\nTemporal/Nexus" : Persist and lookup endpoint for endpoint name
else Nexus Backend Service
  "Alice's\nTemporal/Nexus" -> "Bob's\nTemporal/Nexus" : Make Nexus call
  actor "Bob's\nNexus Worker"
  "Bob's\nTemporal/Nexus" -> "Bob's\nNexus Worker" : Handle Nexus request
else Temporal Workflow Service
  "Bob's\nNexus Worker" -> "Bob's\nTemporal/Nexus" : Start Temporal workflow
  actor "Bob's\nWorkflow Worker"
  "Bob's\nTemporal/Nexus" -> "Bob's\nWorkflow Worker" : Start Temporal workflow
  "Bob's\nTemporal/Nexus" -> "Bob's\nNexus Worker" : Started Temporal workflow
else Nexus Backend Service
  "Bob's\nNexus Worker" -> "Bob's\nTemporal/Nexus" : Complete Nexus request with ALO info
  "Bob's\nTemporal/Nexus" -> "Alice's\nTemporal/Nexus" : Complete Nexus request with ALO info
else Temporal Workflow Service
  "Alice's\nTemporal/Nexus" -> "Alice's\nTemporal/Nexus" : Persist
  "Alice's\nTemporal/Nexus" -> "Alice's\nWorkflow Worker" : Nexus started event
end

== Complete Workflow-based ALO ==

group Service
else Temporal Workflow Service
  "Bob's\nWorkflow Worker" -> "Bob's\nTemporal/Nexus" : Complete workflow command
else Nexus Backend Service
  "Bob's\nTemporal/Nexus" -> "Alice's\nTemporal/Nexus" : ALO complete callback
else Temporal Workflow Service
  "Alice's\nTemporal/Nexus" -> "Alice's\nTemporal/Nexus" : Persist
  "Alice's\nTemporal/Nexus" -> "Alice's\nWorkflow Worker" : Nexus ALO completed event
end

@enduml